# in _config.yml
title: "CDCM tutorial book"
execute:
  execute_notebooks: "off"
author: "Sreehari Manikkan"
repository:
  url: "https://github.com/sjdyke-reth-institute/CDCM_reconfig/tree/redesign/docs"
  path_to_book: "CDCM_book"
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year