# in _config.yml
title: "CDCM Documentation"
execute:
  execute_notebooks: "off"
author: "Predictive Science Laboratory, Purdue University"
repository:
  url: "https://github.com/sjdyke-reth-institute/CDCM_reconfig/tree/main" 
  path_to_book: "docs"
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"
bibtex_bibfiles:
  - references.bib
sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  config:
    add_module_names: False
    bibtex_reference_style: author_year